### ISSUE TITLE
How should I deploy to CloudFlare worker?

### ISSUE THREAD

**Issue by LiuNianJiang** [hronro/cf-download-proxy#1]
I don't seem to find the relevant js file for deployment. Does it exist? Does it allow me to use it in CloudFlare workers?

**Comment by hronro** [comment]
You need Node.js environment and run `npm run build` command to build the final JavaScript code used in Cloudflare Workers.

For deployment, you can upload the code manually or use GitHub Actions to upload it automatically. You can use the GitHub Actions in this repo as an reference.

**Comment by LiuNianJiang** [comment]
Hello, two warnings have appeared.
https://cowtransfer.com/s/0215f49c5f7e42
@foisonocean

**Comment by hronro** [comment]
Probably is not compatible on Windows for now. Could you please file another issue about compatibility of Windows?

PS: You can just simply drag & drop an image to upload it to GitHub.

**Comment by LiuNianJiang** [comment]
> Probably is not compatible on Windows for now. Could you please file another issue about compatibility of Windows?
> 
> PS: You can just simply drag & drop an image to upload it to GitHub.

你好，你是中国人么？如果是的话，我们加一个联系方式直接和你反应可以么？

**Comment by hronro** [comment]
我是中国人。

我不建议使用私下交流的方式，GitHub 本来就是一个开放的交流平台，有什么问题都可以在上面讨论，其他人如果有类似的问题或者有如何修正问题的建议，也可以轻松的加入进来讨论或者从已有的讨论中获取他想要的资讯，这些都是私下交流做不到的。如果你不方便使用英文，你可以直接发中文 issue。

**Comment by LiuNianJiang** [comment]
> 我是中国人。
> 
> 我不建议使用私下交流的方式，GitHub 本来就是一个开放的交流平台，有什么问题都可以在上面讨论，其他人如果有类似的问题或者有如何修正问题的建议，也可以轻松的加入进来讨论或者从已有的讨论中获取他想要的资讯，这些都是私下交流做不到的。如果你不方便使用英文，你可以直接发中文 issue。

会进行issue的提交，方便日后的跟踪，私下交流是因为我担心是我的操作不规范导致的警告出现，如果您不希望私下交流，我会在GitHub上创建issue

**Comment by hronro** [comment]
如果真的是操作不规范导致的，那很有可能别人也会遇到，所以麻烦您直接提交一个新的 issue 就好

**Comment by hronro** [comment]
Probably fixed in 36537b8
