### ISSUE TITLE
please provide cloudflare worker singe index.js

### ISSUE THREAD

**Issue by ghost** [hronro/cf-download-proxy#2]
please if possible make index.js single file so that we can copy and paste and host the site

**Comment by hronro** [comment]
It is a single file after you build it.

**Comment by ghost** [comment]
> It is a single file after you build it.

thank you for response but i guess it would be nice if you can* provide dist folder at this repo directly

**Comment by hronro** [comment]
Thank you for your suggestion, I will put it in the GitHub Releases, so for people who don't want to build it themselves, they can download it from GitHub Releases.
