### ISSUE TITLE
【BUG】下载时输入直链仅下载网页

### ISSUE THREAD

**Issue by LiuNianJiang** [hronro/cf-download-proxy#4]
测试直链：https://box.kaspersky.com/seafhttp/files/eaa88b75-10d2-4273-836f-376a36831c53/KAV21.4.9.326_zh-Hans-CN-xforum_full.exe
但是输入到此程序后下载的仅是网页

**Comment by hronro** [comment]
I can not download this link even if I open the link directly in the browser, probably it's limited on the server's side.

![CleanShot 2021-06-20 at 17 28 10@2x](https://user-images.githubusercontent.com/15059605/122668909-11bd3900-d1ed-11eb-90fa-57170f662b02.png)
